name: Mirror to GitLab

on:
  push:
    branches:
      - "**"
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@gitlab.iit.vn:iit-jsc/dev/nest-core.git
          git push --force gitlab --all
          git push --force gitlab --tags
        env:
          GITLAB_USERNAME: ${{ vars.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
